name: Unit Test

on: 
  push:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install requests python-multipart pytest
      
      - name: Run tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)  # PYTHONPATH 설정
          pytest -v  # 상세 출력 모드로 테스트 실행
